# General settings
auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
# Page Navigation
# Navigation can have children with name and link
# All data is required
#    children:
#      - name: Sub1
#        link: sub1.html
#    	 grandchildren:
#         - name: Sub1
#           link: sub1.html
navigation:
  - name: Home
    description: Appccelerate here
    link: index.html
  - name: Team
    description: Who appccelerates
    link: team.html
  - name: Documentation
    description: How to appccelerate
    link: documentation.html
    children:
      - name: Bootstrapper
        link: bootstrapper.html
      - name: EventBroker
        link: eventbroker.html	
      - name: Distributed Event Broker
        link: distributedeventbroker.html		
      - name: Mapping Event Broker
        link: mappingeventbroker.html			
      - name: Scoping Event Broker
        link: scopingeventbroker.html			
      - name: Evaluation Engine
        link: evaluationengine.html		
      - name: Async
        link: async.html
        grandchildren:
          - name: AsyncWorker
            link: asyncworker.html
          - name: User Interface Thread Synchronizer
            link: userinterfacethreadsynchronizer.html
      - name: State Machine
        link: statemachine.html	
      - name: Road Map
        link: roadmap.html	  
      - name: How to migrate
        link: howtomigrate.html
  - name: Donators
    description: Who supports appcceleration
    link: donators.html
# Team members	
# Full capabilities include
# - name: Your name (*)
#   jobtitle: Your title (*)
#   description: Your description (*)
#   image: img/members/yourname.jpg or img/placeholders/team-member.jpg (*)
#   twitter: Only username
#   facebook:
#   skype:
#   linkedin:
#   googleplus:
#   email:
#   behance:
#   delicious:
#   deviantart:
#   digg:
#   dribbble:
#   dropbox:
#   flickr:
#   forst:
#   github: Only username
#   google:
#   ichat:
#   lastfm:
#   mobypicture:
#   myspace:
#   picase:
#   plixi:
#   rss:
#   stumbleupon:
members:
  - name: Urs Enzler
    jobtitle: Senior Software Architect
    description: The driver who stears Appcceleration on the ideal line for maximum appcceleration.
    image: img/ursenzler.png
    twitter: ursenzler
    github: ursenzler	
  - name: Daniel Marbach
    jobtitle: Senior Developer
    description: The curious mind which constantly appccelerates with new ideas and enthusiasm.
    image: img/danielmarbach.png
    twitter: danielmarbach
    github: danielmarbach
  - name: Philipp Dolder
    jobtitle: Senior Developer
    description: The integration master who appccelerates our build infrastructure continuously.
    image: img/philippdolder.png
    twitter: philippdolder
    github: philippdolder